const SAMPLE = [
  {
    "id": 1,
    "title": "红楼梦",
    "author": "[清] 曹雪芹 著",
    "category": "",
    "year": 1996,
    "rating": 9.6,
    "publisher": "人民文学出版社",
    "desc": "都云作者痴，谁解其中味？",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s1070959.jpg",
    "tags": []
  },
  {
    "id": 2,
    "title": "活着",
    "author": "余华",
    "category": "",
    "year": 2012,
    "rating": 9.4,
    "publisher": "作家出版社",
    "desc": "生的苦难与伟大",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s29053580.jpg",
    "tags": []
  },
  {
    "id": 3,
    "title": "1984",
    "author": "[英] 乔治·奥威尔刘绍铭",
    "category": "",
    "year": 2010,
    "rating": 9.3,
    "publisher": "北京十月文艺出版社",
    "desc": "栗树荫下，我出卖你，你出卖我",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s4371408.jpg",
    "tags": []
  },
  {
    "id": 4,
    "title": "百年孤独",
    "author": "[哥伦比亚] 加西亚·马尔克斯范晔",
    "category": "",
    "year": 2011,
    "rating": 9.3,
    "publisher": "南海出版公司",
    "desc": "魔幻现实主义文学代表作",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s27237850.jpg",
    "tags": []
  },
  {
    "id": 5,
    "title": "飘",
    "author": "[美国] 玛格丽特·米切尔李美华",
    "category": "",
    "year": 2000,
    "rating": 9.3,
    "publisher": "译林出版社",
    "desc": "革命时期的爱情，随风而逝",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s1078958.jpg",
    "tags": []
  },
  {
    "id": 6,
    "title": "三体全集",
    "author": "刘慈欣",
    "category": "",
    "year": 2012,
    "rating": 9.4,
    "publisher": "重庆出版社",
    "desc": "地球往事三部曲",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s28357056.jpg",
    "tags": []
  },
  {
    "id": 7,
    "title": "三国演义（全二册）",
    "author": "[明] 罗贯中",
    "category": "",
    "year": 1998,
    "rating": 9.3,
    "publisher": "人民文学出版社",
    "desc": "是非成败转头空",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s1076932.jpg",
    "tags": []
  },
  {
    "id": 8,
    "title": "动物农场",
    "author": "[英] 乔治·奥威尔荣如德",
    "category": "",
    "year": 2007,
    "rating": 9.2,
    "publisher": "上海译文出版社",
    "desc": "太阳底下并无新事",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s2347590.jpg",
    "tags": []
  },
  {
    "id": 9,
    "title": "房思琪的初恋乐园",
    "author": "林奕含",
    "category": "",
    "year": 2018,
    "rating": 9.2,
    "publisher": "北京联合出版公司",
    "desc": "向死而生的文学绝唱",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s29651121.jpg",
    "tags": []
  },
  {
    "id": 10,
    "title": "福尔摩斯探案全集（上中下）",
    "author": "[英] 阿·柯南道尔丁钟华 等",
    "category": "",
    "year": 1981,
    "rating": 9.3,
    "publisher": "群众出版社",
    "desc": "名侦探的代名词",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s1229240.jpg",
    "tags": []
  },
  {
    "id": 11,
    "title": "白夜行",
    "author": "[日] 东野圭吾刘姿君",
    "category": "",
    "year": 2013,
    "rating": 9.1,
    "publisher": "南海出版公司",
    "desc": "一宗离奇命案牵出跨度近20年步步惊心的故事",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s24514468.jpg",
    "tags": []
  },
  {
    "id": 12,
    "title": "小王子",
    "author": "[法] 圣埃克苏佩里马振聘",
    "category": "",
    "year": 2003,
    "rating": 9,
    "publisher": "人民文学出版社",
    "desc": "献给长成了大人的孩子们",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s1103152.jpg",
    "tags": []
  },
  {
    "id": 13,
    "title": "天龙八部",
    "author": "金庸",
    "category": "",
    "year": 1994,
    "rating": 9.1,
    "publisher": "生活·读书·新知三联书店",
    "desc": "有情皆孽，无人不冤",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s26018275.jpg",
    "tags": []
  },
  {
    "id": 14,
    "title": "撒哈拉的故事",
    "author": "三毛",
    "category": "",
    "year": 2003,
    "rating": 9.2,
    "publisher": "哈尔滨出版社",
    "desc": "游荡的自由灵魂",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s1066570.jpg",
    "tags": []
  },
  {
    "id": 15,
    "title": "安徒生童话故事集",
    "author": "（丹麦）安徒生叶君健",
    "category": "",
    "year": 1997,
    "rating": 9.2,
    "publisher": "人民文学出版社",
    "desc": "为了争取未来的一代",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s1034062.jpg",
    "tags": []
  },
  {
    "id": 16,
    "title": "冰与火之歌（卷一）",
    "author": "[美] 乔治·R. R. 马丁谭光磊",
    "category": "",
    "year": 2005,
    "rating": 9.3,
    "publisher": "重庆出版社",
    "desc": "凛冬将至。无比宏大的世界观",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s1358984.jpg",
    "tags": []
  },
  {
    "id": 17,
    "title": "哈利·波特",
    "author": "J.K.罗琳 (J.K.Rowling)苏农",
    "category": "",
    "year": 2008,
    "rating": 9.7,
    "publisher": "人民文学出版社",
    "desc": "从9¾站台开始的旅程",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s29101586.jpg",
    "tags": []
  },
  {
    "id": 18,
    "title": "沉默的大多数",
    "author": "王小波",
    "category": "",
    "year": 1997,
    "rating": 9.1,
    "publisher": "中国青年出版社",
    "desc": "沉默是沉默者的通行证",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s1447349.jpg",
    "tags": []
  },
  {
    "id": 19,
    "title": "围城",
    "author": "钱锺书",
    "category": "",
    "year": 1991,
    "rating": 8.9,
    "publisher": "人民文学出版社",
    "desc": "幽默的语言和对生活深刻的观察",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s1070222.jpg",
    "tags": []
  },
  {
    "id": 20,
    "title": "人类简史",
    "author": "[以色列] 尤瓦尔·赫拉利林俊宏",
    "category": "",
    "year": 2014,
    "rating": 9.1,
    "publisher": "中信出版社",
    "desc": "跟着人类一同走过十万年",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s27814883.jpg",
    "tags": []
  },
  {
    "id": 21,
    "title": "明朝那些事儿（1-9）",
    "author": "当年明月",
    "category": "",
    "year": 2009,
    "rating": 9.1,
    "publisher": "中国海关出版社",
    "desc": "不拘一格的历史书写",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s3745215.jpg",
    "tags": []
  },
  {
    "id": 22,
    "title": "平凡的世界（全三部）",
    "author": "路遥",
    "category": "",
    "year": 2005,
    "rating": 9,
    "publisher": "人民文学出版社",
    "desc": "中国当代城乡生活全景",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s1144911.jpg",
    "tags": []
  },
  {
    "id": 23,
    "title": "局外人",
    "author": "[法] 阿尔贝·加缪柳鸣九",
    "category": "",
    "year": 2010,
    "rating": 9,
    "publisher": "上海译文出版社",
    "desc": "人生在世，永远也不该演戏作假",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s4468484.jpg",
    "tags": []
  },
  {
    "id": 24,
    "title": "杀死一只知更鸟",
    "author": "[美] 哈珀·李高红梅",
    "category": "",
    "year": 2012,
    "rating": 9.2,
    "publisher": "译林出版社",
    "desc": "有一种东西不能遵循从众原则，那就是——人的良心",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s23128183.jpg",
    "tags": []
  },
  {
    "id": 25,
    "title": "霍乱时期的爱情",
    "author": "[哥伦比亚] 加西亚·马尔克斯杨玲",
    "category": "",
    "year": 2012,
    "rating": 9,
    "publisher": "南海出版公司",
    "desc": "义无反顾地直达爱情的核心",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s11284102.jpg",
    "tags": []
  },
  {
    "id": 26,
    "title": "中国历代政治得失",
    "author": "钱穆",
    "category": "",
    "year": 2001,
    "rating": 9.2,
    "publisher": "生活·读书·新知三联书店",
    "desc": "一部简明的“中国政治制度史”",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s1319205.jpg",
    "tags": []
  },
  {
    "id": 27,
    "title": "笑傲江湖（全四册）",
    "author": "金庸",
    "category": "",
    "year": 1994,
    "rating": 9,
    "publisher": "生活·读书·新知三联书店",
    "desc": "欲练此功，必先自宫",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s2157335.jpg",
    "tags": []
  },
  {
    "id": 28,
    "title": "呐喊",
    "author": "鲁迅",
    "category": "",
    "year": 1973,
    "rating": 9,
    "publisher": "人民文学出版社",
    "desc": "新文学的第一声呐喊",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s4696893.jpg",
    "tags": []
  },
  {
    "id": 29,
    "title": "月亮和六便士",
    "author": "[英] 毛姆傅惟慈",
    "category": "",
    "year": 2006,
    "rating": 9,
    "publisher": "上海译文出版社",
    "desc": "有多少人会经历顿悟，就有更少的人甘愿自我放逐",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s2659208.jpg",
    "tags": []
  },
  {
    "id": 30,
    "title": "肖申克的救赎",
    "author": "[美] 斯蒂芬·金施寄青",
    "category": "",
    "year": 2006,
    "rating": 9.1,
    "publisher": "人民文学出版社",
    "desc": "豆瓣电影Top1原著",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s4007145.jpg",
    "tags": []
  },
  {
    "id": 31,
    "title": "基督山伯爵",
    "author": "大仲马周克希",
    "category": "",
    "year": 1991,
    "rating": 9,
    "publisher": "上海译文出版社",
    "desc": "一个报恩复仇的故事，以法国波旁王朝和七月王朝为背景",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s3248016.jpg",
    "tags": []
  },
  {
    "id": 32,
    "title": "东方快车谋杀案",
    "author": "[英] 阿加莎·克里斯蒂陈尧光",
    "category": "",
    "year": 2006,
    "rating": 9,
    "publisher": "人民文学出版社",
    "desc": "谋杀诡计惊人，波洛的抉择耐人寻味",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s1765799.jpg",
    "tags": []
  },
  {
    "id": 33,
    "title": "万历十五年",
    "author": "[美] 黄仁宇",
    "category": "",
    "year": 1997,
    "rating": 8.9,
    "publisher": "生活·读书·新知三联书店",
    "desc": "见微知著，历史观的颠覆",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s1800355.jpg",
    "tags": []
  },
  {
    "id": 34,
    "title": "追风筝的人",
    "author": "[美] 卡勒德·胡赛尼李继宏",
    "category": "",
    "year": 2006,
    "rating": 8.9,
    "publisher": "上海人民出版社",
    "desc": "为你，千千万万遍",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s1727290.jpg",
    "tags": []
  },
  {
    "id": 35,
    "title": "新名字的故事",
    "author": "[意] 埃莱娜·费兰特陈英",
    "category": "",
    "year": 2017,
    "rating": 9.1,
    "publisher": "人民文学出版社",
    "desc": "探索青年时代的激情、困惑、挣扎、背叛和失去",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s29376146.jpg",
    "tags": []
  },
  {
    "id": 36,
    "title": "失踪的孩子",
    "author": "[意] 埃莱娜·费兰特陈英",
    "category": "",
    "year": 2018,
    "rating": 9.2,
    "publisher": "人民文学出版社",
    "desc": "我的整个生命，只是一场为了提升社会地位的低俗斗争。",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s29799269.jpg",
    "tags": []
  },
  {
    "id": 37,
    "title": "江城",
    "author": "[美] 彼得·海斯勒李雪顺",
    "category": "",
    "year": 2012,
    "rating": 9.1,
    "publisher": "上海译文出版社",
    "desc": "外国人眼中的涪陵",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s7019913.jpg",
    "tags": []
  },
  {
    "id": 38,
    "title": "乡土中国",
    "author": "费孝通",
    "category": "",
    "year": 2006,
    "rating": 9.2,
    "publisher": "上海人民出版社",
    "desc": "中国乡土社会传统文化和社会结构理论研究代表作",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s1665415.jpg",
    "tags": []
  },
  {
    "id": 39,
    "title": "刀锋",
    "author": "[英]毛姆周煦良",
    "category": "",
    "year": 2007,
    "rating": 9,
    "publisher": "上海译文出版社",
    "desc": "一把刀的锋刃不容易越过；因此智者说得救之道是困难的",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s2347562.jpg",
    "tags": []
  },
  {
    "id": 40,
    "title": "嫌疑人X的献身",
    "author": "[日] 东野圭吾刘子倩",
    "category": "",
    "year": 2008,
    "rating": 8.9,
    "publisher": "南海出版公司",
    "desc": "数学好是一种极致的浪漫",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s3254244.jpg",
    "tags": []
  },
  {
    "id": 41,
    "title": "城南旧事",
    "author": "林海音 文",
    "category": "",
    "year": 2003,
    "rating": 9,
    "publisher": "中国青年出版社",
    "desc": "长亭外，古道边，芳草碧连天",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s2654869.jpg",
    "tags": []
  },
  {
    "id": 42,
    "title": "寻路中国",
    "author": "[美] 彼得·海斯勒李雪顺",
    "category": "",
    "year": 2011,
    "rating": 9,
    "publisher": "上海译文出版社",
    "desc": "《纽约客》驻北京记者驾车漫游中国大陆的经历",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s32271209.jpg",
    "tags": []
  },
  {
    "id": 43,
    "title": "射雕英雄传（全四册）",
    "author": "金庸",
    "category": "",
    "year": 1999,
    "rating": 9,
    "publisher": "生活·读书·新知三联书店",
    "desc": "侠之大者，为国为民",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s2157336.jpg",
    "tags": []
  },
  {
    "id": 44,
    "title": "白鹿原",
    "author": "陈忠实",
    "category": "",
    "year": 2012,
    "rating": 9.2,
    "publisher": "人民文学出版社",
    "desc": "一轴关于我们民族灵魂的现实主义画卷",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s28111905.jpg",
    "tags": []
  },
  {
    "id": 45,
    "title": "我与地坛",
    "author": "史铁生",
    "category": "",
    "year": 2002,
    "rating": 9.1,
    "publisher": "春风文艺出版社",
    "desc": "这是你的罪孽与福祉",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s1151479.jpg",
    "tags": []
  },
  {
    "id": 46,
    "title": "格林童话全集",
    "author": "[德国]格林兄弟魏以新",
    "category": "",
    "year": 1994,
    "rating": 9,
    "publisher": "人民文学出版社",
    "desc": "一本有教育意义的书",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s1134341.jpg",
    "tags": []
  },
  {
    "id": 47,
    "title": "傲慢与偏见",
    "author": "[英] 奥斯丁张玲",
    "category": "",
    "year": 1993,
    "rating": 8.9,
    "publisher": "人民文学出版社",
    "desc": "所有现代言情小说的母体",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s4250062.jpg",
    "tags": []
  },
  {
    "id": 48,
    "title": "黄金时代",
    "author": "王小波",
    "category": "",
    "year": 1999,
    "rating": 8.9,
    "publisher": "花城出版社",
    "desc": "我想爱，想吃，还想在一瞬间变成天上半明半暗的云",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s1076372.jpg",
    "tags": []
  },
  {
    "id": 49,
    "title": "野草",
    "author": "鲁迅",
    "category": "",
    "year": 1973,
    "rating": 9.4,
    "publisher": "人民文学出版社",
    "desc": "我以这一丛野草，在明与暗，生与死，过去与未来之际，献于友与仇，人与兽，爱者与不爱者之前作证。",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s2364689.jpg",
    "tags": []
  },
  {
    "id": 50,
    "title": "无人生还",
    "author": "[英] 阿加莎・克里斯蒂祁阿红",
    "category": "",
    "year": 2008,
    "rating": 8.9,
    "publisher": "人民文学出版社",
    "desc": "童谣杀人案",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s2962510.jpg",
    "tags": []
  },
  {
    "id": 51,
    "title": "艺术的故事",
    "author": "[英] 贡布里希 (Sir E.H.Gombrich)范景中",
    "category": "",
    "year": 2008,
    "rating": 9.6,
    "publisher": "广西美术出版社",
    "desc": "从最早的洞窟绘画到当今的实验艺术",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s3219163.jpg",
    "tags": []
  },
  {
    "id": 52,
    "title": "历史深处的忧虑",
    "author": "林达",
    "category": "",
    "year": 1997,
    "rating": 9,
    "publisher": "生活·读书·新知三联书店",
    "desc": "窥见美国社会的一扇窗",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s1768916.jpg",
    "tags": []
  },
  {
    "id": 53,
    "title": "文学回忆录",
    "author": "木心 口述",
    "category": "",
    "year": 2013,
    "rating": 9.1,
    "publisher": "广西师范大学出版社",
    "desc": "木心留给世界的礼物",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s24611679.jpg",
    "tags": []
  },
  {
    "id": 54,
    "title": "神雕侠侣",
    "author": "金庸有1996年11月北平第4次印本",
    "category": "",
    "year": 1994,
    "rating": 8.9,
    "publisher": "生活·读书·新知三联书店",
    "desc": "至情至性，情大于武",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s26018916.jpg",
    "tags": []
  },
  {
    "id": 55,
    "title": "悲惨世界（上中下）",
    "author": "[法] 雨果李丹",
    "category": "",
    "year": 1992,
    "rating": 9,
    "publisher": "人民文学出版社",
    "desc": "现实主义与浪漫主义的至高杰作",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s4521754.jpg",
    "tags": []
  },
  {
    "id": 56,
    "title": "彷徨",
    "author": "鲁迅",
    "category": "",
    "year": 1973,
    "rating": 9.1,
    "publisher": "人民文学出版社",
    "desc": "路漫漫其修远兮，吾将上下而求索",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s33500305.jpg",
    "tags": []
  },
  {
    "id": 57,
    "title": "史记（全十册）",
    "author": "司马迁（索隐）司马贞，（正义）张守节",
    "category": "",
    "year": 1982,
    "rating": 9.5,
    "publisher": "中华书局",
    "desc": "史家之绝唱，无韵之离骚",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s1953384.jpg",
    "tags": []
  },
  {
    "id": 58,
    "title": "许三观卖血记",
    "author": "余华",
    "category": "",
    "year": 1998,
    "rating": 8.8,
    "publisher": "南海出版公司",
    "desc": "以博大的温情描绘磨难中的人生",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s1074291.jpg",
    "tags": []
  },
  {
    "id": 59,
    "title": "上帝掷骰子吗",
    "author": "曹天元",
    "category": "",
    "year": 2006,
    "rating": 9.2,
    "publisher": "辽宁教育出版社",
    "desc": "量子物理史话",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s1486674.jpg",
    "tags": []
  },
  {
    "id": 60,
    "title": "朝花夕拾",
    "author": "鲁迅",
    "category": "",
    "year": 1972,
    "rating": 8.9,
    "publisher": "人民文学出版社",
    "desc": "在纷扰中寻出一点闲静",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s2875823.jpg",
    "tags": []
  },
  {
    "id": 61,
    "title": "树上的男爵",
    "author": "[意] 伊塔洛·卡尔维诺吴正仪",
    "category": "",
    "year": 2012,
    "rating": 9.1,
    "publisher": "译林出版社",
    "desc": "是不是真的只有先与人疏离，才能最终与他们在一起？",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s8968135.jpg",
    "tags": []
  },
  {
    "id": 62,
    "title": "卡拉马佐夫兄弟",
    "author": "[俄] 费奥多尔·陀思妥耶夫斯基荣如德",
    "category": "",
    "year": 2006,
    "rating": 9.4,
    "publisher": "上海译文出版社",
    "desc": "错综复杂的社会、家庭矛盾和人性悲剧",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s2059791.jpg",
    "tags": []
  },
  {
    "id": 63,
    "title": "哭泣的骆驼",
    "author": "三毛",
    "category": "",
    "year": 2003,
    "rating": 8.9,
    "publisher": "哈尔滨出版社",
    "desc": "沙漠中寻常的生与死",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s1020454.jpg",
    "tags": []
  },
  {
    "id": 64,
    "title": "邓小平时代",
    "author": "[美] 傅高义冯克利",
    "category": "",
    "year": 2013,
    "rating": 9.2,
    "publisher": "生活·读书·新知三联书店",
    "desc": "个人命运背后的历史变局",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s24516687.jpg",
    "tags": []
  },
  {
    "id": 65,
    "title": "诗经",
    "author": "孔丘 编订",
    "category": "",
    "year": 2006,
    "rating": 9.4,
    "publisher": "北京出版社",
    "desc": "思无邪",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s1979223.jpg",
    "tags": []
  },
  {
    "id": 66,
    "title": "看见",
    "author": "柴静",
    "category": "",
    "year": 2013,
    "rating": 8.8,
    "publisher": "广西师范大学出版社",
    "desc": "在这里看见中国",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s24468373.jpg",
    "tags": []
  },
  {
    "id": 67,
    "title": "灿烂千阳",
    "author": "[美] 卡勒德·胡赛尼李继宏",
    "category": "",
    "year": 2007,
    "rating": 8.8,
    "publisher": "上海人民出版社",
    "desc": "唯有希望与爱可以驱散阴霾",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s2651394.jpg",
    "tags": []
  },
  {
    "id": 68,
    "title": "浪潮之巅",
    "author": "吴军",
    "category": "",
    "year": 2011,
    "rating": 9,
    "publisher": "电子工业出版社",
    "desc": "了解IT领域的入门读物",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s6807265.jpg",
    "tags": []
  },
  {
    "id": 69,
    "title": "西游记（全二册）",
    "author": "吴承恩黄肃秋 注释",
    "category": "",
    "year": 2004,
    "rating": 8.9,
    "publisher": "人民文学出版社",
    "desc": "神魔皆有人情，精魅亦通世故",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s1627374.jpg",
    "tags": []
  },
  {
    "id": 70,
    "title": "台北人",
    "author": "白先勇",
    "category": "",
    "year": 2010,
    "rating": 8.9,
    "publisher": "广西师范大学出版社",
    "desc": "白先勇短篇小说集",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s4526465.jpg",
    "tags": []
  },
  {
    "id": 71,
    "title": "永恒的终结",
    "author": "[美] 艾萨克·阿西莫夫崔正男",
    "category": "",
    "year": 2014,
    "rating": 9,
    "publisher": "江苏凤凰文艺出版社",
    "desc": "关于时间旅行的终极奥秘和恢宏构想",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s29555070.jpg",
    "tags": []
  },
  {
    "id": 72,
    "title": "悉达多",
    "author": "[德] 赫尔曼·黑塞杨玉功 译",
    "category": "",
    "year": 2009,
    "rating": 9,
    "publisher": "上海人民出版社",
    "desc": "在那最绝望的一刹那，他突然听到了生命之河永恒的声音……",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s6790238.jpg",
    "tags": []
  },
  {
    "id": 73,
    "title": "人间词话",
    "author": "王国维",
    "category": "",
    "year": 1998,
    "rating": 9,
    "publisher": "上海古籍出版社",
    "desc": "以新眼光评旧文学",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s9130587.jpg",
    "tags": []
  },
  {
    "id": 74,
    "title": "窗边的小豆豆",
    "author": "[日] 黑柳彻子 著赵玉皎",
    "category": "",
    "year": 2003,
    "rating": 8.7,
    "publisher": "南海出版公司",
    "desc": "真正懂孩子的教育经",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s1067911.jpg",
    "tags": []
  },
  {
    "id": 75,
    "title": "爱你就像爱生命",
    "author": "王小波",
    "category": "",
    "year": 2008,
    "rating": 8.8,
    "publisher": "上海锦绣文章出版社",
    "desc": "王小波与李银河的两地书",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s4661043.jpg",
    "tags": []
  },
  {
    "id": 76,
    "title": "我们仨",
    "author": "杨绛",
    "category": "",
    "year": 2003,
    "rating": 8.7,
    "publisher": "生活·读书·新知三联书店",
    "desc": "家庭生活回忆录",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s1015872.jpg",
    "tags": []
  },
  {
    "id": 77,
    "title": "故事新编",
    "author": "鲁迅",
    "category": "",
    "year": 1973,
    "rating": 9.4,
    "publisher": "人民文学出版社",
    "desc": "拾取古代传说，取一点因由，随意点染",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s2364685.jpg",
    "tags": []
  },
  {
    "id": 78,
    "title": "一个叫欧维的男人决定去死",
    "author": "[瑞典] 弗雷德里克·巴克曼宁蒙",
    "category": "",
    "year": 2015,
    "rating": 9,
    "publisher": "四川文艺出版社",
    "desc": "这个发生在瑞典的故事，如生命庆典般绚丽斑斓",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s29071620.jpg",
    "tags": []
  },
  {
    "id": 79,
    "title": "最好的告别",
    "author": "[美] 阿图·葛文德（Atul Gawande）王一方 主编",
    "category": "",
    "year": 2015,
    "rating": 9,
    "publisher": "浙江人民出版社",
    "desc": "关于衰老与死亡，你必须知道的常识",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s28355811.jpg",
    "tags": []
  },
  {
    "id": 80,
    "title": "巨人的陨落",
    "author": "[英] 肯·福莱特于大卫",
    "category": "",
    "year": 2016,
    "rating": 8.9,
    "publisher": "江苏凤凰文艺出版社",
    "desc": "五个家族，一场战争",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s28668834.jpg",
    "tags": []
  },
  {
    "id": 81,
    "title": "道德经",
    "author": "黄元吉",
    "category": "",
    "year": 1996,
    "rating": 9.4,
    "publisher": "陕西人民出版社",
    "desc": "中国历史上首部完整的哲学著作",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s1045431.jpg",
    "tags": []
  },
  {
    "id": 82,
    "title": "唐诗三百首",
    "author": "蘅塘退士",
    "category": "",
    "year": 1998,
    "rating": 9.4,
    "publisher": "中华书局",
    "desc": "熟读唐诗三百首，不会吟诗也会吟",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s1008848.jpg",
    "tags": []
  },
  {
    "id": 83,
    "title": "罗杰疑案",
    "author": "[英] 阿加莎·克里斯蒂常禾",
    "category": "",
    "year": 2013,
    "rating": 9.2,
    "publisher": "新星出版社",
    "desc": " ",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s25814002.jpg",
    "tags": []
  },
  {
    "id": 84,
    "title": "鼠疫",
    "author": "(法)阿尔贝·加缪刘方",
    "category": "",
    "year": 2013,
    "rating": 9,
    "publisher": "上海译文出版社",
    "desc": "用别样的监禁生活再现某种监禁生活，与用不存在的事表现真事同等合理",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s27003191.jpg",
    "tags": []
  },
  {
    "id": 85,
    "title": "呼兰河传",
    "author": "萧红",
    "category": "",
    "year": 2005,
    "rating": 8.9,
    "publisher": "百花文艺出版社",
    "desc": "萧红的童年往事",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s1167060.jpg",
    "tags": []
  },
  {
    "id": 86,
    "title": "教父",
    "author": "[美]马里奥·普佐周汉林",
    "category": "",
    "year": 1997,
    "rating": 9,
    "publisher": "译林出版社",
    "desc": "“教父三部曲”电影原著",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s2832939.jpg",
    "tags": []
  },
  {
    "id": 87,
    "title": "海子的诗",
    "author": "海子",
    "category": "",
    "year": 1999,
    "rating": 8.9,
    "publisher": "人民文学出版社",
    "desc": " ",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s1067491.jpg",
    "tags": []
  },
  {
    "id": 88,
    "title": "这些人，那些事",
    "author": "吴念真",
    "category": "",
    "year": 2011,
    "rating": 8.8,
    "publisher": "译林出版社",
    "desc": "平淡叙述下的惊心动魄",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s6828981.jpg",
    "tags": []
  },
  {
    "id": 89,
    "title": "飞鸟集",
    "author": "[印] 罗宾德拉纳德·泰戈尔徐翰林",
    "category": "",
    "year": 2004,
    "rating": 8.9,
    "publisher": "哈尔滨出版社",
    "desc": "一个淡泊清透的世界",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s1044902.jpg",
    "tags": []
  },
  {
    "id": 90,
    "title": "你当像鸟飞往你的山",
    "author": "[美] 塔拉·韦斯特弗任爱红",
    "category": "",
    "year": 2019,
    "rating": 8.8,
    "publisher": "南海出版公司",
    "desc": "我来自一个极少有人能想象的家庭，教育给了我新世界",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s33492346.jpg",
    "tags": []
  },
  {
    "id": 91,
    "title": "人生的枷锁",
    "author": "[英] 毛姆张柏然",
    "category": "",
    "year": 2007,
    "rating": 9,
    "publisher": "上海译文出版社",
    "desc": "在混沌纷扰的生活漩流中，寻求人生的真谛",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s3983958.jpg",
    "tags": []
  },
  {
    "id": 92,
    "title": "看不见的城市",
    "author": "[意大利]伊塔洛·卡尔维诺张宓",
    "category": "",
    "year": 2006,
    "rating": 8.8,
    "publisher": "译林出版社",
    "desc": "每一座城市都只在想象中耸立，又在描述中坍圮",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s1804710.jpg",
    "tags": []
  },
  {
    "id": 93,
    "title": "鹿鼎记（全五册）",
    "author": "金庸",
    "category": "",
    "year": 2008,
    "rating": 8.8,
    "publisher": "广州出版社 花城出版社",
    "desc": "武侠的解构，流氓的狂欢",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s3134040.jpg",
    "tags": []
  },
  {
    "id": 94,
    "title": "斯通纳",
    "author": "[美] 约翰·威廉斯杨向荣",
    "category": "",
    "year": 2016,
    "rating": 8.8,
    "publisher": "上海人民出版社",
    "desc": "即使不能拥有完美的生活，所幸追求过完整的自我",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s28332051.jpg",
    "tags": []
  },
  {
    "id": 95,
    "title": "梦里花落知多少",
    "author": "三毛",
    "category": "",
    "year": 2007,
    "rating": 8.8,
    "publisher": "北京十月文艺出版社",
    "desc": "哀而不伤",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s2393243.jpg",
    "tags": []
  },
  {
    "id": 96,
    "title": "边城",
    "author": "沈从文",
    "category": "",
    "year": 2002,
    "rating": 8.7,
    "publisher": "北岳文艺出版社",
    "desc": "一切充满了善，然而到处是不凑巧",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s1595557.jpg",
    "tags": []
  },
  {
    "id": 97,
    "title": "叫魂",
    "author": "[美] 孔飞力陈兼",
    "category": "",
    "year": 2012,
    "rating": 9,
    "publisher": "生活·读书·新知三联书店 上海三联书店",
    "desc": "1768年中国妖术大恐慌",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s9015481.jpg",
    "tags": []
  },
  {
    "id": 98,
    "title": "王尔德童话",
    "author": "[英] 王尔德王林",
    "category": "",
    "year": 2003,
    "rating": 9.1,
    "publisher": "译林出版社",
    "desc": "一颗纯美纯善、永难泯灭的童心",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s2019056.jpg",
    "tags": []
  },
  {
    "id": 99,
    "title": "冬牧场",
    "author": "李娟",
    "category": "",
    "year": 2012,
    "rating": 9,
    "publisher": "新星出版社",
    "desc": "阿勒泰的精灵",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s8958901.jpg",
    "tags": []
  },
  {
    "id": 100,
    "title": "时间简史",
    "author": "[英] 史蒂芬·霍金许明贤",
    "category": "",
    "year": 2010,
    "rating": 8.8,
    "publisher": "湖南科学技术出版社",
    "desc": "探索时间和空间的核心秘密",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s1914861.jpg",
    "tags": []
  },
  {
    "id": 101,
    "title": "金色梦乡",
    "author": "[日] 伊坂幸太郎李彦桦",
    "category": "",
    "year": 2010,
    "rating": 9,
    "publisher": "译林出版社",
    "desc": "伊坂幸太郎代表作",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s4444885.jpg",
    "tags": []
  },
  {
    "id": 102,
    "title": "美的历程",
    "author": "李泽厚",
    "category": "",
    "year": 2009,
    "rating": 9.2,
    "publisher": "生活·读书·新知三联书店",
    "desc": "中国美学经典之作",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s3893343.jpg",
    "tags": []
  },
  {
    "id": 103,
    "title": "人生的智慧",
    "author": "[德] 阿图尔·叔本华韦启昌",
    "category": "",
    "year": 2008,
    "rating": 9.2,
    "publisher": "上海人民出版社",
    "desc": "对世俗、实用问题深刻而透彻的讨论",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s4619775.jpg",
    "tags": []
  },
  {
    "id": 104,
    "title": "陆犯焉识",
    "author": "严歌苓",
    "category": "",
    "year": 2011,
    "rating": 8.8,
    "publisher": "作家出版社",
    "desc": "翻手为苍凉，覆手为繁华",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s6987353.jpg",
    "tags": []
  },
  {
    "id": 105,
    "title": "一个陌生女人的来信",
    "author": "[奥] 斯台芬·茨威格张玉书",
    "category": "",
    "year": 2007,
    "rating": 8.7,
    "publisher": "上海译文出版社",
    "desc": "暗恋的极致",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s2611329.jpg",
    "tags": []
  },
  {
    "id": 106,
    "title": "献给阿尔吉侬的花束",
    "author": "[美] 丹尼尔·凯斯陈澄和",
    "category": "",
    "year": 2015,
    "rating": 9.1,
    "publisher": "广西师范大学出版社",
    "desc": "当声称能改造智能的科学实验选中心智障碍主角",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s28050760.jpg",
    "tags": []
  },
  {
    "id": 107,
    "title": "孽子",
    "author": "白先勇",
    "category": "",
    "year": 2010,
    "rating": 9.1,
    "publisher": "广西师范大学出版社",
    "desc": "写给那一群， 在最深最深的黑夜里， 独自彷徨街头， 无所依归的孩子们",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s6240330.jpg",
    "tags": []
  },
  {
    "id": 108,
    "title": "离开的，留下的",
    "author": "[意] 埃莱娜·费兰特陈英",
    "category": "",
    "year": 2017,
    "rating": 8.8,
    "publisher": "人民文学出版社",
    "desc": "探索中年的虚无、困惑、野心和近乎残暴的爱",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s29535271.jpg",
    "tags": []
  },
  {
    "id": 109,
    "title": "國史大綱（上下）",
    "author": "錢穆",
    "category": "",
    "year": 2013,
    "rating": 9.3,
    "publisher": "商務印書館",
    "desc": "钱穆中国通史",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s23922774.jpg",
    "tags": []
  },
  {
    "id": 110,
    "title": "苏菲的世界",
    "author": "[挪] 乔斯坦·贾德萧宝森",
    "category": "",
    "year": 2007,
    "rating": 8.8,
    "publisher": "作家出版社",
    "desc": "哲学启蒙书",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s3042670.jpg",
    "tags": []
  },
  {
    "id": 111,
    "title": "史蒂夫·乔布斯传",
    "author": "[美] 沃尔特·艾萨克森管延圻",
    "category": "",
    "year": 2011,
    "rating": 8.7,
    "publisher": "中信出版社",
    "desc": "完美主义者的最高形态",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s6974202.jpg",
    "tags": []
  },
  {
    "id": 112,
    "title": "万水千山走遍",
    "author": "三毛",
    "category": "",
    "year": 2003,
    "rating": 8.8,
    "publisher": "哈尔滨出版社",
    "desc": "从遥远的撒哈拉到敦煌戈壁",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s1099483.jpg",
    "tags": []
  },
  {
    "id": 113,
    "title": "十万个为什么",
    "author": "少年儿童出版社",
    "category": "",
    "year": null,
    "rating": 9.1,
    "publisher": " ",
    "desc": " ",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s2619779.jpg",
    "tags": []
  },
  {
    "id": 114,
    "title": "经济学原理（上下）",
    "author": "[美] 曼昆梁小民",
    "category": "",
    "year": 2003,
    "rating": 9.1,
    "publisher": "机械工业出版社",
    "desc": "经济学家们的世界观",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s1785715.jpg",
    "tags": []
  },
  {
    "id": 115,
    "title": "爱的艺术",
    "author": "[美] 艾·弗洛姆李健鸣",
    "category": "",
    "year": 2008,
    "rating": 8.8,
    "publisher": "上海译文出版社",
    "desc": "谦恭地、勇敢地、真诚地和有纪律地爱他人",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s2990934.jpg",
    "tags": []
  },
  {
    "id": 116,
    "title": "昨日的世界",
    "author": "[奥] 斯蒂芬·茨威格舒昌善",
    "category": "",
    "year": 2004,
    "rating": 9.2,
    "publisher": "广西师范大学出版社",
    "desc": "一个高贵而残破的昨日镜像",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s1121598.jpg",
    "tags": []
  },
  {
    "id": 117,
    "title": "孩子你慢慢来",
    "author": "龙应台",
    "category": "",
    "year": 2009,
    "rating": 8.7,
    "publisher": "生活·读书·新知三联书店",
    "desc": "我们现在怎样做母亲",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s4124434.jpg",
    "tags": []
  },
  {
    "id": 118,
    "title": "小径分岔的花园",
    "author": "[阿根廷] 豪·路·博尔赫斯王永年",
    "category": "",
    "year": 2015,
    "rating": 8.9,
    "publisher": "上海译文出版社",
    "desc": "一个谜语，谜底正是时间",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s29746559.jpg",
    "tags": []
  },
  {
    "id": 119,
    "title": "浮生六记",
    "author": "（清）沈复",
    "category": "",
    "year": 1999,
    "rating": 8.8,
    "publisher": "人民文学出版社",
    "desc": "苟不记之笔墨，未免有辜彼苍之厚",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s2280094.jpg",
    "tags": []
  },
  {
    "id": 120,
    "title": "四世同堂",
    "author": "老舍",
    "category": "",
    "year": 2008,
    "rating": 9.3,
    "publisher": "北京十月文艺出版社",
    "desc": "北平沦陷时代广大平民的悲惨遭遇",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s3228699.jpg",
    "tags": []
  },
  {
    "id": 121,
    "title": "我也有一个梦想",
    "author": "林达",
    "category": "",
    "year": 2004,
    "rating": 9,
    "publisher": "生活·读书·新知三联书店",
    "desc": "在法治国家里，民众怎样运用法律",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s2170315.jpg",
    "tags": []
  },
  {
    "id": 122,
    "title": "绿毛水怪",
    "author": "王小波",
    "category": "",
    "year": 2009,
    "rating": 9,
    "publisher": "时代文艺出版社",
    "desc": "我们好象在池塘的水底，从一个月亮走向另一个月亮",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s3675595.jpg",
    "tags": []
  },
  {
    "id": 123,
    "title": "不能承受的生命之轻",
    "author": "米兰·昆德拉许钧",
    "category": "",
    "year": 2010,
    "rating": 8.8,
    "publisher": "上海译文出版社",
    "desc": " ",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s4421443.jpg",
    "tags": []
  },
  {
    "id": 124,
    "title": "海的女儿",
    "author": "安徒生叶君健",
    "category": "",
    "year": 1978,
    "rating": 9.1,
    "publisher": "上海译文出版社",
    "desc": " ",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s4133656.jpg",
    "tags": []
  },
  {
    "id": 125,
    "title": "亮剑",
    "author": "都梁",
    "category": "",
    "year": 2005,
    "rating": 8.9,
    "publisher": "解放军文艺出版社",
    "desc": "面对强大的对手，明知不敌，也要毅然亮剑",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s9950828.jpg",
    "tags": []
  },
  {
    "id": 126,
    "title": "古文观止",
    "author": "吴楚材",
    "category": "",
    "year": 1987,
    "rating": 9.1,
    "publisher": "中华书局",
    "desc": "收录自先秦至明末的散文二百二十二篇",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s1325863.jpg",
    "tags": []
  },
  {
    "id": 127,
    "title": "情书",
    "author": "[日] 岩井俊二穆晓芳",
    "category": "",
    "year": 2004,
    "rating": 8.6,
    "publisher": "天津人民出版社",
    "desc": "一场同名同姓的误会，两段可贵的爱情",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s1127135.jpg",
    "tags": []
  },
  {
    "id": 128,
    "title": "面纱",
    "author": "(英)W.萨默塞特·毛姆阮景林",
    "category": "",
    "year": 2012,
    "rating": 8.7,
    "publisher": "重庆",
    "desc": "揭去生活的面纱",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s9038826.jpg",
    "tags": []
  },
  {
    "id": 129,
    "title": "球状闪电",
    "author": "刘慈欣",
    "category": "",
    "year": 2005,
    "rating": 8.7,
    "publisher": "四川科学技术出版社",
    "desc": "量子之外，没有真相",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s26040205.jpg",
    "tags": []
  },
  {
    "id": 130,
    "title": "倾城之恋",
    "author": "张爱玲",
    "category": "",
    "year": 2006,
    "rating": 8.7,
    "publisher": "北京十月文艺出版社",
    "desc": "“一对平凡的夫妻”之间的“一点真心”",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s4638950.jpg",
    "tags": []
  },
  {
    "id": 131,
    "title": "受戒",
    "author": "汪曾祺",
    "category": "",
    "year": 1987,
    "rating": 9.3,
    "publisher": "漓江出版社",
    "desc": "江南乡镇民间生活，健康淳朴的人性",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s3628082.jpg",
    "tags": []
  },
  {
    "id": 132,
    "title": "送你一颗子弹",
    "author": "刘瑜",
    "category": "",
    "year": 2010,
    "rating": 8.6,
    "publisher": "上海三联书店",
    "desc": "在这本书里，被“审视”的东西杂七杂八",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s4243447.jpg",
    "tags": []
  },
  {
    "id": 133,
    "title": "我的阿勒泰",
    "author": "李娟",
    "category": "",
    "year": 2010,
    "rating": 8.8,
    "publisher": "云南人民出版社",
    "desc": "描写疆北阿勒泰地区生活和风情的原生态散文集",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s6180859.jpg",
    "tags": []
  },
  {
    "id": 134,
    "title": "故事",
    "author": "[美] 罗伯特·麦基周铁东",
    "category": "",
    "year": 2014,
    "rating": 9.2,
    "publisher": "天津人民出版社",
    "desc": "材质、结构、风格和银幕剧作的原理",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s27598249.jpg",
    "tags": []
  },
  {
    "id": 135,
    "title": "阿勒泰的角落",
    "author": "李娟",
    "category": "",
    "year": 2010,
    "rating": 9.1,
    "publisher": "万卷出版公司",
    "desc": "白雪和阳光，青草和白桦林",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s6185540.jpg",
    "tags": []
  },
  {
    "id": 136,
    "title": "温柔的夜",
    "author": "三毛",
    "category": "",
    "year": 2007,
    "rating": 9.1,
    "publisher": "北京十月文艺出版社",
    "desc": "三毛在加纳利群岛的生活",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s2391798.jpg",
    "tags": []
  },
  {
    "id": 137,
    "title": "目送",
    "author": "龙应台",
    "category": "",
    "year": 2009,
    "rating": 8.6,
    "publisher": "生活·读书·新知三联书店",
    "desc": "不必追",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s3984108.jpg",
    "tags": []
  },
  {
    "id": 138,
    "title": "亲爱的安德烈",
    "author": "龙应台",
    "category": "",
    "year": 2008,
    "rating": 8.6,
    "publisher": "人民文学出版社",
    "desc": "弭平代沟，跨越文化阻隔",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s3993878.jpg",
    "tags": []
  },
  {
    "id": 139,
    "title": "霸王别姬",
    "author": "李碧华",
    "category": "",
    "year": 1999,
    "rating": 9.1,
    "publisher": "人民文学出版社",
    "desc": "人间，只是抹去了脂粉的脸",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s24964086.jpg",
    "tags": []
  },
  {
    "id": 140,
    "title": "野火集",
    "author": "龙应台",
    "category": "",
    "year": 2005,
    "rating": 8.8,
    "publisher": "文汇出版社",
    "desc": "中国人，你为什么不生气",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s1469589.jpg",
    "tags": []
  },
  {
    "id": 141,
    "title": "德米安",
    "author": "[德] 赫尔曼·黑塞丁君君",
    "category": "",
    "year": 2009,
    "rating": 9,
    "publisher": "上海人民出版社",
    "desc": "少年辛克莱寻找通向自身之路的艰辛历程",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s3979854.jpg",
    "tags": []
  },
  {
    "id": 142,
    "title": "银河系漫游指南",
    "author": "[英] 道格拉斯·亚当斯徐百柯",
    "category": "",
    "year": 2005,
    "rating": 8.8,
    "publisher": "四川科学技术出版社",
    "desc": "一场穿越银河的冒险",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s3696740.jpg",
    "tags": []
  },
  {
    "id": 143,
    "title": "枪炮、病菌与钢铁",
    "author": "[美] 贾雷德·戴蒙德谢延光",
    "category": "",
    "year": 2006,
    "rating": 8.7,
    "publisher": "上海世纪出版集团",
    "desc": "人类社会的命运",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s1738643.jpg",
    "tags": []
  },
  {
    "id": 144,
    "title": "麦琪的礼物",
    "author": "[美] 欧·亨利张经浩",
    "category": "",
    "year": 2003,
    "rating": 8.6,
    "publisher": "上海社会科学院出版社",
    "desc": "日常的奇迹",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s1137441.jpg",
    "tags": []
  },
  {
    "id": 145,
    "title": "失明症漫记",
    "author": "[葡] 若泽·萨拉马戈范维信",
    "category": "",
    "year": 2014,
    "rating": 9.1,
    "publisher": "南海出版公司",
    "desc": "失明症迅速蔓延，整个城市陷入一场空前的灾难",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s27217828.jpg",
    "tags": []
  },
  {
    "id": 146,
    "title": "激荡三十年",
    "author": "吴晓波",
    "category": "",
    "year": 2008,
    "rating": 8.6,
    "publisher": "中信出版社",
    "desc": "中国企业1978—2008",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s3203360.jpg",
    "tags": []
  },
  {
    "id": 147,
    "title": "半生缘",
    "author": "张爱玲",
    "category": "",
    "year": 2006,
    "rating": 8.6,
    "publisher": "北京十月文艺出版社",
    "desc": "世钧，我们回不去了",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s2838737.jpg",
    "tags": []
  },
  {
    "id": 148,
    "title": "我不知道该说什么，关于死亡还是爱情",
    "author": "S.A.阿列克谢耶维奇方祖芳",
    "category": "",
    "year": 2014,
    "rating": 9,
    "publisher": "花城出版社/铁葫芦图书",
    "desc": "真实记录切尔诺贝利核灾难事件",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s28313152.jpg",
    "tags": []
  },
  {
    "id": 149,
    "title": "社会心理学",
    "author": "[美] 戴维·迈尔斯张智勇",
    "category": "",
    "year": 2006,
    "rating": 9,
    "publisher": "人民邮电出版社",
    "desc": "人们是如何思索、影响他人并与他人建立联系的",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s1670932.jpg",
    "tags": []
  },
  {
    "id": 150,
    "title": "尼罗河上的惨案",
    "author": "[英] 阿加莎·克里斯蒂宫英海",
    "category": "",
    "year": 2006,
    "rating": 8.7,
    "publisher": "人民文学出版社",
    "desc": "阿加莎·克里斯蒂代表作",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s1683067.jpg",
    "tags": []
  },
  {
    "id": 151,
    "title": "解忧杂货店",
    "author": "[日] 东野圭吾李盈春",
    "category": "",
    "year": 2014,
    "rating": 8.5,
    "publisher": "南海出版公司",
    "desc": "现代人内心流失的东西，这家杂货店能帮你找回",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s27264181.jpg",
    "tags": []
  },
  {
    "id": 152,
    "title": "罗生门",
    "author": "[日]芥川龙之介林少华",
    "category": "",
    "year": 2008,
    "rating": 8.7,
    "publisher": "上海译文出版社",
    "desc": "人生，远比地狱更像地狱",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s3435158.jpg",
    "tags": []
  },
  {
    "id": 153,
    "title": "你好，旧时光（上 下）",
    "author": "八月长安",
    "category": "",
    "year": 2009,
    "rating": 8.7,
    "publisher": "新世界出版社",
    "desc": "原作名切题",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s4293097.jpg",
    "tags": []
  },
  {
    "id": 154,
    "title": "渴望生活",
    "author": "[美] 欧文·斯通常涛",
    "category": "",
    "year": 2008,
    "rating": 9.2,
    "publisher": "北京十月文艺出版社",
    "desc": "梵高悲惨而成就辉煌的人生",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s3099438.jpg",
    "tags": []
  },
  {
    "id": 155,
    "title": "棋王",
    "author": "阿城",
    "category": "",
    "year": 1999,
    "rating": 8.8,
    "publisher": "作家出版社",
    "desc": "我从未真正见过火，也未见过毁灭，更不知新生",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s26237958.jpg",
    "tags": []
  },
  {
    "id": 156,
    "title": "天朝的崩溃",
    "author": "茅海建",
    "category": "",
    "year": 2005,
    "rating": 9.1,
    "publisher": "生活·读书·新知三联书店",
    "desc": "鸦片战争再研究",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s1681072.jpg",
    "tags": []
  },
  {
    "id": 157,
    "title": "万物有灵且美",
    "author": "[英] 吉米·哈利种衍伦",
    "category": "",
    "year": 2010,
    "rating": 8.8,
    "publisher": "中国城市出版社",
    "desc": "活泼的生命完全无须借助魔法，便能对我们述说至美至真的故事",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s4093514.jpg",
    "tags": []
  },
  {
    "id": 158,
    "title": "人间草木",
    "author": "汪曾祺",
    "category": "",
    "year": 2005,
    "rating": 9,
    "publisher": "江苏文艺出版社",
    "desc": "我就是要这样香，香得痛痛快快",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s1201610.jpg",
    "tags": []
  },
  {
    "id": 159,
    "title": "罪与罚",
    "author": "[俄] 陀思妥耶夫斯基岳麟",
    "category": "",
    "year": 2006,
    "rating": 9.1,
    "publisher": "上海译文出版社",
    "desc": "描绘人内心的全部深度",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s1790246.jpg",
    "tags": []
  },
  {
    "id": 160,
    "title": "我的天才女友",
    "author": "[意] 埃莱娜·费兰特陈英",
    "category": "",
    "year": 2017,
    "rating": 8.5,
    "publisher": "人民文学出版社",
    "desc": "“那不勒斯四部曲”第一部，两个女人，50年的友谊和战争",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s29164777.jpg",
    "tags": []
  },
  {
    "id": 161,
    "title": "茶馆",
    "author": "老舍",
    "category": "",
    "year": 2002,
    "rating": 9,
    "publisher": "人民文学出版社",
    "desc": "清末、民初、抗战胜利以后三个历史时期的北京生活风貌",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s33516550.jpg",
    "tags": []
  },
  {
    "id": 162,
    "title": "荆棘鸟",
    "author": "[澳] 考琳·麦卡洛曾胡",
    "category": "",
    "year": 1998,
    "rating": 8.6,
    "publisher": "译林出版社",
    "desc": "澳洲乱世情",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s2781615.jpg",
    "tags": []
  },
  {
    "id": 163,
    "title": "倚天屠龙记(共四册)",
    "author": "金庸",
    "category": "",
    "year": 1999,
    "rating": 8.6,
    "publisher": "三联书店",
    "desc": "不识张郎是张郎",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s1829709.jpg",
    "tags": []
  },
  {
    "id": 164,
    "title": "总统是靠不住的",
    "author": "林达",
    "category": "",
    "year": 2004,
    "rating": 8.8,
    "publisher": "生活·读书·新知三联书店",
    "desc": "美国政治法律制度的基本原理和操作细节",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s2170316.jpg",
    "tags": []
  },
  {
    "id": 165,
    "title": "最好的我们",
    "author": "八月长安",
    "category": "",
    "year": 2013,
    "rating": 8.7,
    "publisher": "湖南文艺出版社",
    "desc": "耿耿余淮",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s26720726.jpg",
    "tags": []
  },
  {
    "id": 166,
    "title": "全球通史",
    "author": "(美) 斯塔夫里阿诺斯吴象婴",
    "category": "",
    "year": 2012,
    "rating": 9.1,
    "publisher": "北京大学出版社",
    "desc": "从史前史到21世纪",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s29796663.jpg",
    "tags": []
  },
  {
    "id": 167,
    "title": "民主的细节",
    "author": "刘瑜",
    "category": "",
    "year": 2009,
    "rating": 8.6,
    "publisher": "上海三联书店",
    "desc": "公民养成手册",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s4146437.jpg",
    "tags": []
  },
  {
    "id": 168,
    "title": "顾城的诗",
    "author": "顾城",
    "category": "",
    "year": 1998,
    "rating": 8.8,
    "publisher": "人民文学出版社",
    "desc": "火焰是我们诗歌唯一的读者",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s1024472.jpg",
    "tags": []
  },
  {
    "id": 169,
    "title": "草房子",
    "author": "曹文轩",
    "category": "",
    "year": 2009,
    "rating": 9,
    "publisher": "江苏少年儿童出版社",
    "desc": "男孩桑桑刻骨铭心、终身难忘的六年小学生活",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s2652540.jpg",
    "tags": []
  },
  {
    "id": 170,
    "title": "一句顶一万句",
    "author": "刘震云",
    "category": "",
    "year": 2009,
    "rating": 8.7,
    "publisher": "长江文艺出版社",
    "desc": "一句胜过千年",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s6916838.jpg",
    "tags": []
  },
  {
    "id": 171,
    "title": "上学记",
    "author": "何兆武 口述",
    "category": "",
    "year": 2006,
    "rating": 8.9,
    "publisher": "生活·读书·新知三联书店",
    "desc": "20世纪中国知识分子的心灵史",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s1950424.jpg",
    "tags": []
  },
  {
    "id": 172,
    "title": "认识电影",
    "author": "[美] 路易斯·贾内梯焦雄屏",
    "category": "",
    "year": 2007,
    "rating": 8.9,
    "publisher": "世界图书出版公司",
    "desc": "电影入门经典之作",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s28274132.jpg",
    "tags": []
  },
  {
    "id": 173,
    "title": "九州·缥缈录",
    "author": "江南",
    "category": "",
    "year": 2015,
    "rating": 8.8,
    "publisher": "人民文学出版社",
    "desc": "一轴腥风血雨的乱世长卷，中国版《冰与火之歌》",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s28332484.jpg",
    "tags": []
  },
  {
    "id": 174,
    "title": "孙子兵法",
    "author": "孙武郭化若",
    "category": "",
    "year": 2006,
    "rating": 9.4,
    "publisher": "上海古籍出版社",
    "desc": "我国最古老最杰出的一部兵书",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s2142329.jpg",
    "tags": []
  },
  {
    "id": 175,
    "title": "一千零一夜",
    "author": "纳训",
    "category": "",
    "year": 2003,
    "rating": 8.7,
    "publisher": "人民文学出版社",
    "desc": "阿拉伯地区的古代民间传说",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s1070937.jpg",
    "tags": []
  },
  {
    "id": 176,
    "title": "雷雨",
    "author": "曹禺",
    "category": "",
    "year": 1999,
    "rating": 8.6,
    "publisher": "人民文学出版社",
    "desc": "一幕人生大悲剧，在一个雷雨夜爆发",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s23579217.jpg",
    "tags": []
  },
  {
    "id": 177,
    "title": "雨季不再来",
    "author": "三毛",
    "category": "",
    "year": 2007,
    "rating": 8.7,
    "publisher": "北京十月文艺出版社",
    "desc": "三毛少女时代的成长感受",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s2563279.jpg",
    "tags": []
  },
  {
    "id": 178,
    "title": "海风中失落的血色馈赠",
    "author": "[加拿大] 阿利斯泰尔·麦克劳德陈以侃",
    "category": "",
    "year": 2015,
    "rating": 9.1,
    "publisher": "上海文艺出版社",
    "desc": "男女之间、父母与子女之间紧密的纽带和难以逾越的鸿沟",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s28061231.jpg",
    "tags": []
  },
  {
    "id": 179,
    "title": "水浒传（全二册）",
    "author": "[明] 施耐庵",
    "category": "",
    "year": 1997,
    "rating": 8.6,
    "publisher": "人民文学出版社",
    "desc": "替天行道",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s1436519.jpg",
    "tags": []
  },
  {
    "id": 180,
    "title": "此生未完成",
    "author": "于娟",
    "category": "",
    "year": 2011,
    "rating": 8.9,
    "publisher": "湖南科技出版社",
    "desc": "一个母亲、妻子、女儿的生命日记",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s6343233.jpg",
    "tags": []
  },
  {
    "id": 181,
    "title": "一桩事先张扬的凶杀案",
    "author": "[哥伦比亚] 加西亚·马尔克斯魏然",
    "category": "",
    "year": 2013,
    "rating": 8.7,
    "publisher": "南海出版公司",
    "desc": "我如此急切地想要讲述这桩案件，也许是它最终确定了我的作家生涯",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s26546959.jpg",
    "tags": []
  },
  {
    "id": 182,
    "title": "正见",
    "author": "宗萨蒋扬钦哲仁波切姚仁喜",
    "category": "",
    "year": 2007,
    "rating": 8.8,
    "publisher": "中国友谊出版公司",
    "desc": "佛陀的证悟",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s1993421.jpg",
    "tags": []
  },
  {
    "id": 183,
    "title": "理想国",
    "author": "[古希腊] 柏拉图郭斌和",
    "category": "",
    "year": 1986,
    "rating": 8.8,
    "publisher": "商务印书馆",
    "desc": "人类历史上最早的乌托邦",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s1068535.jpg",
    "tags": []
  },
  {
    "id": 184,
    "title": "从一到无穷大",
    "author": "[美] G. 伽莫夫暴永宁 译",
    "category": "",
    "year": 2002,
    "rating": 9.1,
    "publisher": "科学出版社",
    "desc": "科学中的事实和臆测",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s2516920.jpg",
    "tags": []
  },
  {
    "id": 185,
    "title": "额尔古纳河右岸",
    "author": "迟子建",
    "category": "",
    "year": 2005,
    "rating": 9,
    "publisher": "北京十月文艺出版社",
    "desc": "东北少数民族鄂温克人生存现状及百年沧桑",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s3380714.jpg",
    "tags": []
  },
  {
    "id": 186,
    "title": "青铜时代",
    "author": "王小波",
    "category": "",
    "year": 1997,
    "rating": 8.7,
    "publisher": "花城出版社",
    "desc": "唐人传奇贯注现代情趣",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s1072541.jpg",
    "tags": []
  },
  {
    "id": 187,
    "title": "牧羊少年奇幻之旅",
    "author": "[巴西] 保罗·柯艾略丁文林",
    "category": "",
    "year": 2009,
    "rating": 8.5,
    "publisher": "南海出版公司",
    "desc": "你自己就是最大的宝藏",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s3668327.jpg",
    "tags": []
  },
  {
    "id": 188,
    "title": "强风吹拂",
    "author": "三浦紫苑林佩瑾",
    "category": "",
    "year": 2015,
    "rating": 9,
    "publisher": "广西师范大学出版社",
    "desc": "明明这么痛苦，这么难过，为什么就是不能放弃跑步？",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s27914268.jpg",
    "tags": []
  },
  {
    "id": 189,
    "title": "庄子",
    "author": "孙通海 译注方勇 译注",
    "category": "",
    "year": 2007,
    "rating": 9.4,
    "publisher": "中华书局",
    "desc": "野马也，尘埃也，生物之以息相吹也",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s5765615.jpg",
    "tags": []
  },
  {
    "id": 190,
    "title": "圣经",
    "author": "中国基督教协会",
    "category": "",
    "year": null,
    "rating": 9,
    "publisher": " ",
    "desc": "上帝说，要有光",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s1677577.jpg",
    "tags": []
  },
  {
    "id": 191,
    "title": "繁花",
    "author": "金宇澄",
    "category": "",
    "year": 2013,
    "rating": 8.7,
    "publisher": "上海文艺出版社",
    "desc": "海上繁花，请静观静读",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s26037307.jpg",
    "tags": []
  },
  {
    "id": 192,
    "title": "黑客与画家",
    "author": "[美] Paul Graham阮一峰",
    "category": "",
    "year": 2011,
    "rating": 8.7,
    "publisher": "人民邮电出版社",
    "desc": "硅谷创业之父Paul Graham文集",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s4669554.jpg",
    "tags": []
  },
  {
    "id": 193,
    "title": "银河帝国：基地七部曲",
    "author": "[美] 艾萨克·阿西莫夫叶李华",
    "category": "",
    "year": 2015,
    "rating": 9.5,
    "publisher": "江苏凤凰文艺出版社",
    "desc": "阿西莫夫经典科幻小说",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s28284246.jpg",
    "tags": []
  },
  {
    "id": 194,
    "title": "众病之王",
    "author": "[美] 悉达多·穆克吉李虎",
    "category": "",
    "year": 2013,
    "rating": 9.1,
    "publisher": "中信出版社",
    "desc": "癌症传",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s24598159.jpg",
    "tags": []
  },
  {
    "id": 195,
    "title": "中国哲学简史",
    "author": "冯友兰赵复三",
    "category": "",
    "year": 2004,
    "rating": 8.9,
    "publisher": "新世界出版社",
    "desc": "中国哲学入门书",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s1069364.jpg",
    "tags": []
  },
  {
    "id": 196,
    "title": "火星救援",
    "author": "[美] 安迪·威尔陈灼",
    "category": "",
    "year": 2015,
    "rating": 8.9,
    "publisher": "译林出版社",
    "desc": "跟火星来一场不是你死就是我活的过家家游戏",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s28284337.jpg",
    "tags": []
  },
  {
    "id": 197,
    "title": "巨流河",
    "author": "齐邦媛",
    "category": "",
    "year": 2010,
    "rating": 8.7,
    "publisher": "生活·读书·新知三联书店",
    "desc": "两代人从巨流河到哑口海的故事",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s4494379.jpg",
    "tags": []
  },
  {
    "id": 198,
    "title": "象棋的故事",
    "author": "[奥] 斯台芬·茨威格张玉书",
    "category": "",
    "year": 2007,
    "rating": 9.1,
    "publisher": "上海译文出版社",
    "desc": "纳粹法西斯对人心灵的折磨及摧残",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s2897060.jpg",
    "tags": []
  },
  {
    "id": 199,
    "title": "你一生的故事",
    "author": "[美] 特德·姜李克勤",
    "category": "",
    "year": 2015,
    "rating": 8.7,
    "publisher": "译林出版社",
    "desc": "特德·姜科幻小说集",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s28033064.jpg",
    "tags": []
  },
  {
    "id": 200,
    "title": "论语",
    "author": "中华书局",
    "category": "",
    "year": null,
    "rating": 9.1,
    "publisher": " ",
    "desc": "仁远乎哉？我欲仁，斯仁至矣",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s5804746.jpg",
    "tags": []
  },
  {
    "id": 201,
    "title": "张爱玲文集",
    "author": "张爱玲",
    "category": "",
    "year": 1992,
    "rating": 8.9,
    "publisher": "安徽文艺出版社",
    "desc": " ",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s1662165.jpg",
    "tags": []
  },
  {
    "id": 202,
    "title": "金锁记",
    "author": "张爱玲",
    "category": "",
    "year": 2005,
    "rating": 8.6,
    "publisher": "哈尔滨出版社",
    "desc": "一个小商人家庭出身的女子曹七巧的心灵变迁历程",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s2976745.jpg",
    "tags": []
  },
  {
    "id": 203,
    "title": "恶意",
    "author": "[日] 东野圭吾娄美莲",
    "category": "",
    "year": 2016,
    "rating": 8.7,
    "publisher": "南海出版公司",
    "desc": " ",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s29069735.jpg",
    "tags": []
  },
  {
    "id": 204,
    "title": "简爱（英文全本）",
    "author": "[英] 夏洛蒂·勃朗特",
    "category": "",
    "year": 2003,
    "rating": 8.5,
    "publisher": "世界图书出版公司",
    "desc": "灰姑娘在十九世纪",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s5924326.jpg",
    "tags": []
  },
  {
    "id": 205,
    "title": "当呼吸化为空气",
    "author": "[美] 保罗·卡拉尼什何雨珈",
    "category": "",
    "year": 2016,
    "rating": 8.8,
    "publisher": "猫头鹰文化·浙江文艺出版社",
    "desc": "你在死亡中探究生命的意义，你见证生前的呼吸化作死后的空气",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s29423902.jpg",
    "tags": []
  },
  {
    "id": 206,
    "title": "美丽新世界",
    "author": "[英] 赫胥黎陈超",
    "category": "",
    "year": 2017,
    "rating": 9.1,
    "publisher": "上海译文出版社",
    "desc": " ",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s29477615.jpg",
    "tags": []
  },
  {
    "id": 207,
    "title": "毛姆短篇小说精选集",
    "author": "[英] 威廉·萨默塞特·毛姆冯亦代",
    "category": "",
    "year": 2012,
    "rating": 9,
    "publisher": "译林出版社",
    "desc": "在各种光怪陆离的场景中，迷失的人性引发了一连串的悲剧",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s24174596.jpg",
    "tags": []
  },
  {
    "id": 208,
    "title": "夏洛的网",
    "author": "[美] E.B.怀特任溶溶",
    "category": "",
    "year": 2004,
    "rating": 8.6,
    "publisher": "上海译文出版社",
    "desc": "一个蜘蛛和小猪的故事，写给孩子，也写给大人",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s1120437.jpg",
    "tags": []
  },
  {
    "id": 209,
    "title": "设计中的设计",
    "author": "[日] 原研哉朱锷",
    "category": "",
    "year": 2006,
    "rating": 8.6,
    "publisher": "山东人民出版社",
    "desc": "日常生活的无限可能性",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s2165932.jpg",
    "tags": []
  },
  {
    "id": 210,
    "title": "二手时间",
    "author": "[白俄] S. A. 阿列克谢耶维奇吕宁思",
    "category": "",
    "year": 2016,
    "rating": 8.8,
    "publisher": "中信出版集团",
    "desc": "用最为细小的马赛克拼出了一幅完整的后苏联时代图景",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s28397415.jpg",
    "tags": []
  },
  {
    "id": 211,
    "title": "荒原狼",
    "author": "[德]赫尔曼·黑塞赵登荣",
    "category": "",
    "year": 2008,
    "rating": 9,
    "publisher": "上海译文出版社",
    "desc": "“超现实主义”风格作品，德国的《尤利西斯》",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s3286369.jpg",
    "tags": []
  },
  {
    "id": 212,
    "title": "挪威的森林",
    "author": "[日] 村上春树林少华",
    "category": "",
    "year": 2007,
    "rating": 8.5,
    "publisher": "上海译文出版社",
    "desc": "像喜欢春天的熊一样",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s27312538.jpg",
    "tags": []
  },
  {
    "id": 213,
    "title": "狂热分子",
    "author": "[美] 埃里克·霍弗梁永安",
    "category": "",
    "year": 2011,
    "rating": 8.9,
    "publisher": "广西师范大学出版社",
    "desc": "探讨群众运动的共有特征",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s28036829.jpg",
    "tags": []
  },
  {
    "id": 214,
    "title": "佐贺的超级阿嬷",
    "author": "[日] 岛田洋七陈宝莲",
    "category": "",
    "year": 2007,
    "rating": 8.7,
    "publisher": "南海出版公司",
    "desc": "乐观的外婆却总有神奇的办法",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s3922462.jpg",
    "tags": []
  },
  {
    "id": 215,
    "title": "牡丹亭",
    "author": "汤显祖",
    "category": "",
    "year": 1963,
    "rating": 9,
    "publisher": "人民文学出版社",
    "desc": "不到园林，怎知春色如许",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s1075414.jpg",
    "tags": []
  },
  {
    "id": 216,
    "title": "稻草人手记",
    "author": "三毛",
    "category": "",
    "year": 2009,
    "rating": 8.9,
    "publisher": "北京十月文艺出版社",
    "desc": "三毛在加纳利群岛上的生活",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s3667048.jpg",
    "tags": []
  },
  {
    "id": 217,
    "title": "世界尽头与冷酷仙境",
    "author": "[日] 村上春树林少华",
    "category": "",
    "year": 2002,
    "rating": 8.6,
    "publisher": "上海译文出版社",
    "desc": "交叉平行蒙太奇",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s1801057.jpg",
    "tags": []
  },
  {
    "id": 218,
    "title": "香水",
    "author": "[德] 帕·聚斯金德李清华",
    "category": "",
    "year": 2009,
    "rating": 8.9,
    "publisher": "上海译文出版社",
    "desc": " ",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s3867373.jpg",
    "tags": []
  },
  {
    "id": 219,
    "title": "世界的凛冬",
    "author": "[英] 肯·福莱特陈杰",
    "category": "",
    "year": 2017,
    "rating": 8.8,
    "publisher": "江苏凤凰文艺出版社",
    "desc": "我亲眼目睹，每一个迈向死亡的生命都在热烈地生长",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s29331058.jpg",
    "tags": []
  },
  {
    "id": 220,
    "title": "步履不停",
    "author": "[日] 是枝裕和郑有杰",
    "category": "",
    "year": 2017,
    "rating": 8.7,
    "publisher": "北京联合出版公司",
    "desc": "人生路上，步履不停，总有那么一点来不及",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s29425921.jpg",
    "tags": []
  },
  {
    "id": 221,
    "title": "ZOO",
    "author": "[日] 乙一李颖秋",
    "category": "",
    "year": 2007,
    "rating": 8.6,
    "publisher": "当代世界出版社",
    "desc": "噩梦中的一丝温度",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s2756239.jpg",
    "tags": []
  },
  {
    "id": 222,
    "title": "金阁寺",
    "author": "[日] 三岛由纪夫唐月梅",
    "category": "",
    "year": 2009,
    "rating": 8.7,
    "publisher": "上海译文出版社",
    "desc": "他的犯罪动机是对美的嫉妒",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s3511590.jpg",
    "tags": []
  },
  {
    "id": 223,
    "title": "社会契约论",
    "author": "卢梭何兆武",
    "category": "",
    "year": 2003,
    "rating": 8.8,
    "publisher": "商务印书馆",
    "desc": "一个国家只能有一个契约",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s3470220.jpg",
    "tags": []
  },
  {
    "id": 224,
    "title": "人类的群星闪耀时",
    "author": "[奥] 斯蒂芬·茨威格舒昌善",
    "category": "",
    "year": 2004,
    "rating": 8.7,
    "publisher": "广西师范大学出版社",
    "desc": "十四个影响人类文明的瞬间",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s1134166.jpg",
    "tags": []
  },
  {
    "id": 225,
    "title": "影响力",
    "author": "[美] 罗伯特·西奥迪尼陈叙",
    "category": "",
    "year": 2006,
    "rating": 8.6,
    "publisher": "中国人民大学出版社",
    "desc": "营销防骗指南",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s1657785.jpg",
    "tags": []
  },
  {
    "id": 226,
    "title": "通往奴役之路",
    "author": "弗里德利希・冯・哈耶克王明毅",
    "category": "",
    "year": 1997,
    "rating": 8.8,
    "publisher": "中国社会科学出版社",
    "desc": "古典自由主义杰作",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s8879166.jpg",
    "tags": []
  },
  {
    "id": 227,
    "title": "老人与海",
    "author": "海明威吴劳",
    "category": "",
    "year": 1999,
    "rating": 8.4,
    "publisher": "上海译文出版社",
    "desc": "正是悲壮赋予生活以意义",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s1050021.jpg",
    "tags": []
  },
  {
    "id": 228,
    "title": "安娜·卡列尼娜",
    "author": "[俄] 列夫·托尔斯泰草婴",
    "category": "",
    "year": 2007,
    "rating": 9.2,
    "publisher": "上海文艺出版社",
    "desc": " ",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s5763939.jpg",
    "tags": []
  },
  {
    "id": 229,
    "title": "少年凯歌",
    "author": "陈凯歌",
    "category": "",
    "year": 2001,
    "rating": 9.2,
    "publisher": "人民文学出版社",
    "desc": " ",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s24399718.jpg",
    "tags": []
  },
  {
    "id": 230,
    "title": "规训与惩罚",
    "author": "[法] 米歇尔·福柯刘北成",
    "category": "",
    "year": 2003,
    "rating": 9.2,
    "publisher": "生活·读书·新知三联书店",
    "desc": "伴随着惩罚的人性化，自由反而日益丧失了",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s2522397.jpg",
    "tags": []
  },
  {
    "id": 231,
    "title": "多情剑客无情剑(上、中、下)",
    "author": "古龙",
    "category": "",
    "year": 1991,
    "rating": 8.7,
    "publisher": "海天出版社",
    "desc": "流水滔滔斩不断，情丝百结冲不破",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s1641357.jpg",
    "tags": []
  },
  {
    "id": 232,
    "title": "骆驼祥子",
    "author": "老舍",
    "category": "",
    "year": 2000,
    "rating": 8.4,
    "publisher": "人民文学出版社",
    "desc": "旧中国老北京贫苦市民的典型命运",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s1146040.jpg",
    "tags": []
  },
  {
    "id": 233,
    "title": "哈姆莱特",
    "author": "[英] 莎士比亚朱生豪",
    "category": "",
    "year": 2001,
    "rating": 8.6,
    "publisher": "人民文学出版社",
    "desc": "生存还是毁灭，这是一个值得思考的问题",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s27009357.jpg",
    "tags": []
  },
  {
    "id": 234,
    "title": "了不起的盖茨比",
    "author": "[美] 斯科特·菲茨杰拉德邓若虚",
    "category": "",
    "year": 2012,
    "rating": 8.7,
    "publisher": "南海出版公司",
    "desc": " ",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s9110246.jpg",
    "tags": []
  },
  {
    "id": 235,
    "title": "告白",
    "author": "[日]凑佳苗丁世佳",
    "category": "",
    "year": 2010,
    "rating": 8.5,
    "publisher": "哈尔滨出版社",
    "desc": " ",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s4425090.jpg",
    "tags": []
  },
  {
    "id": 236,
    "title": "2001太空漫游",
    "author": "[英] 阿瑟·克拉克郝明义",
    "category": "",
    "year": 2007,
    "rating": 9.1,
    "publisher": "上海人民出版社",
    "desc": "科幻三巨头之一阿瑟·克拉克代表作",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s2798862.jpg",
    "tags": []
  },
  {
    "id": 237,
    "title": "海底两万里",
    "author": "[法国] 儒尔·凡尔纳沈国华",
    "category": "",
    "year": 2002,
    "rating": 8.5,
    "publisher": "译林出版社",
    "desc": "你听说过鹦鹉螺号吗？",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s1817666.jpg",
    "tags": []
  },
  {
    "id": 238,
    "title": "美国宪政历程",
    "author": "任东来",
    "category": "",
    "year": 2014,
    "rating": 9.1,
    "publisher": "中国法制出版社",
    "desc": "25个案例异彩纷呈，美国宪政的酸甜苦辣尽在其中",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s24503563.jpg",
    "tags": []
  },
  {
    "id": 239,
    "title": "别闹了，费曼先生",
    "author": "[美] 理查德·费曼吴程远",
    "category": "",
    "year": 1997,
    "rating": 8.9,
    "publisher": "生活·读书·新知三联书店",
    "desc": "科学顽童的故事",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s1027286.jpg",
    "tags": []
  },
  {
    "id": 240,
    "title": "一个人的村庄",
    "author": "刘亮程",
    "category": "",
    "year": 2006,
    "rating": 8.9,
    "publisher": "春风文艺出版社",
    "desc": "他是真正的作家，也是真正的农民",
    "cover": "https://img9.doubanio.com/view/subject/s/public/s9018034.jpg",
    "tags": []
  },
  {
    "id": 241,
    "title": "西方哲学史（上卷）",
    "author": "[英] 罗素何兆武",
    "category": "",
    "year": 1963,
    "rating": 8.9,
    "publisher": "商务印书馆",
    "desc": "西方哲学史及其与从古代到现代的政治、社会情况的联系",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s1562997.jpg",
    "tags": []
  },
  {
    "id": 242,
    "title": "长袜子皮皮",
    "author": "[瑞典] 阿斯特丽德·林格伦李之义",
    "category": "",
    "year": 1999,
    "rating": 9,
    "publisher": "中国少年儿童出版社",
    "desc": " ",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s1290828.jpg",
    "tags": []
  },
  {
    "id": 243,
    "title": "欢乐英雄",
    "author": "古龙",
    "category": "",
    "year": 2005,
    "rating": 8.8,
    "publisher": "珠海出版社",
    "desc": "坚持自己的信念，在贫穷中获得欢乐与友谊",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s2508587.jpg",
    "tags": []
  },
  {
    "id": 244,
    "title": "不存在的骑士",
    "author": "[意] 伊塔洛·卡尔维诺吴正仪",
    "category": "",
    "year": 2012,
    "rating": 8.8,
    "publisher": "译林出版社",
    "desc": " ",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s8972061.jpg",
    "tags": []
  },
  {
    "id": 245,
    "title": "社会性动物",
    "author": "Elliot Aronson邢占军",
    "category": "",
    "year": 2007,
    "rating": 9.1,
    "publisher": "华东师范大学出版社",
    "desc": "美国社会心理学的《圣经》",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s2783843.jpg",
    "tags": []
  },
  {
    "id": 246,
    "title": "尘埃落定",
    "author": "阿来",
    "category": "",
    "year": 1998,
    "rating": 8.5,
    "publisher": "人民文学出版社",
    "desc": "一个傻子的土司家族传奇",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s9140762.jpg",
    "tags": []
  },
  {
    "id": 247,
    "title": "如父如子",
    "author": "[日] 是枝裕和丹勇",
    "category": "",
    "year": 2018,
    "rating": 8.9,
    "publisher": "湖南文艺出版社",
    "desc": " ",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s29707420.jpg",
    "tags": []
  },
  {
    "id": 248,
    "title": "过于喧嚣的孤独",
    "author": "(捷克) 赫拉巴尔杨乐云",
    "category": "",
    "year": 2011,
    "rating": 8.8,
    "publisher": "北京十月文艺出版社",
    "desc": "我为它而活着，并为写它推迟了我的死亡",
    "cover": "https://img1.doubanio.com/view/subject/s/public/s24422879.jpg",
    "tags": []
  },
  {
    "id": 249,
    "title": "长日将尽",
    "author": "[英] 石黑一雄冯涛",
    "category": "",
    "year": 2018,
    "rating": 8.8,
    "publisher": "上海译文出版社",
    "desc": " ",
    "cover": "https://img3.doubanio.com/view/subject/s/public/s29738720.jpg",
    "tags": []
  },
  {
    "id": 250,
    "title": "被讨厌的勇气",
    "author": "岸见一郎渠海霞",
    "category": "",
    "year": 2015,
    "rating": 8.6,
    "publisher": "机械工业出版社",
    "desc": " ",
    "cover": "https://img2.doubanio.com/view/subject/s/public/s33323852.jpg",
    "tags": []
  }
]